# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: PROJECTTEAMFORYOU.WindowLayout
PackageVersion: 1.4.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: WindowLayout
ReleaseDate: 2026-10-10
AppsAndFeaturesEntries:
- DisplayName: WindowLayout
  Publisher: PROJECTTEAMFORYOU
  ProductCode: WindowLayout
Installers:
- Architecture: x64
  InstallerUrl: https://dl.windowlayout.com/v1.4.0/WindowLayout-1.4.0-setup-x64.exe
  InstallerSha256: 435C051C5F83F6C0F1E7A56C76F7701089721395DF5413DAC9EA6AF64D3B4FE5
ManifestType: installer
ManifestVersion: 1.6.0
