# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: PROJECTTEAMFORYOU.WindowLayout
PackageVersion: 1.6.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: WindowLayout
ReleaseDate: 2026-10-10
AppsAndFeaturesEntries:
- DisplayName: WindowLayout
  Publisher: PROJECTTEAMFORYOU
  ProductCode: WindowLayout
Installers:
- Architecture: x64
  InstallerUrl: https://dl.windowlayout.com/v1.6.0/WindowLayout-1.6.0-setup-x64.exe
  InstallerSha256: EFA9059189F8BF7548DD1BEE1937524B8AE5E519BFC65EE9710BB41781F744B7
ManifestType: installer
ManifestVersion: 1.6.0
