# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: PROJECTTEAMFORYOU.WindowLayout
PackageVersion: 1.2.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: WindowLayout
ReleaseDate: 2026-10-05
AppsAndFeaturesEntries:
- DisplayName: WindowLayout
  Publisher: PROJECTTEAMFORYOU
  ProductCode: WindowLayout
Installers:
- Architecture: x64
  InstallerUrl: https://dl.windowlayout.com/v1.2.0/WindowLayout-1.2.0-setup-x64.exe
  InstallerSha256: ABD361E6F3AE2D49ABE78EADEC33AF7AE2494106CBD3C7C364118FF59A551364
ManifestType: installer
ManifestVersion: 1.6.0
