# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: WindowPin.WindowPin
PackageVersion: 3.0.7
MinimumOSVersion: 10.0.17763.0
InstallerType: portable
UpgradeBehavior: install
Commands:
- windowpin
Installers:
- Architecture: x64
  InstallerUrl: https://dl.windowpin.com/stable/3.0.7/WindowPin-3.0.7-win-x64.exe
  InstallerSha256: E862C30437CCE82A4632D8EFC7397C7053F3ADEEDD7F2D6BB1271478832474A1
ManifestType: installer
ManifestVersion: 1.12.0
