# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: PROJECTTEAMFORYOU.WindowLayout
PackageVersion: 1.5.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: WindowLayout
ReleaseDate: 2026-10-10
AppsAndFeaturesEntries:
- DisplayName: WindowLayout
  Publisher: PROJECTTEAMFORYOU
  ProductCode: WindowLayout
Installers:
- Architecture: x64
  InstallerUrl: https://dl.windowlayout.com/v1.5.0/WindowLayout-1.5.0-setup-x64.exe
  InstallerSha256: FF800C1F56CD0E1411824DF89CC373901E41DA6436A3AE4AD4AECDF76158A3BD
ManifestType: installer
ManifestVersion: 1.6.0
