# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Projectteamforyou.OmniDesk
PackageVersion: 1.2.2
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/work517/omnidesk-desktop/releases/download/v1.2.2/OmniDesk-Windows-Setup.exe
  InstallerSha256: 5F36666B5712CAA814FA5BC2CC9214354695EEA67E75BD3EB71A36D5E7E4008C
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-08
